version: '3'

services:
    mongodb_container:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: R00t
            MONGO_INITDB_ROOT_PASSWORD: R00t_123
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_container:/data/db
        networks:
            - network_application

    app:
        depends_on:
            - mongodb_container
        build:
            context: .
            dockerfile: Dockerfile
        container_name: node-app
        ports:
            - 3333:3333
        command: npm run dev
        volumes:
            - .:/home/node/app
        networks:
            - network_application

volumes:
    mongodb_data_container:

networks:
    network_application:
        driver: bridge